import { getSession } from 'next-auth/client'
import Head from 'next/head'
import Feed from '../components/Feed/Feed'
import Header from '../components/Header/Header'
import Login from '../components/Login/Login'
import Sidebar from '../components/Sidebar/Sidebar'
import Widgets from '../components/Widgets/Widgets'
import { getDocs, query, collection, orderBy } from '@firebase/firestore'
import { db } from '../firebase/firebase'
export default function Home({ session, posts }) {
  if (!session) return <Login />
  return (
    <div className="h-screen bg-gray-100 overflow-hidden" >
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Facebook_icon_2013.svg/768px-Facebook_icon_2013.svg.png"
          type="image/icon" />
      </Head>
      <Header />
      <main className="flex">
        <Sidebar />
        <Feed posts={posts} />
        <Widgets />
      </main>
    </div>
  )
}
export async function getServerSideProps(context) {
  // Get the user
  const session = await getSession(context);
  const post = await getDocs(query(collection(db, 'posts'), orderBy('timestamp', 'desc')))
  const docs = post.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))
  return {
    props: {
      session,
      posts: docs
    }
  }
}
